runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic

handlers:
- url: /.*
  script: auto
  secure: always 